services:
  - type: web
    name: whiteboard-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true 